FROM ros:foxy-ros-base-focal

# Actualizar la clave GPG
RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-keys AD19BAB3CBF125EA

# Agregar el repositorio de ROS
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'

RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-keys F42ED6FBAB17C654


RUN apt-get update && apt-get install -y \
    ros-foxy-turtlesim \
    ros-foxy-ros1-bridge \
    && rm -rf /var/lib/apt/lists/* \
    qtbase5-dev \
    libqt5widgets5 \
    x11-apps

RUN echo "source /opt/ros/foxy/setup.bash" >> ~/.bashrc
