FROM ros:noetic-ros-base-focal

RUN apt-get update && apt-get install -y \
    ros-noetic-rosbridge-server \
    ros-noetic-rosbridge-suite \
    && rm -rf /var/lib/apt/lists/*

RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
